"""add devices and components tables

Revision ID: cf03667c1e93
Revises: 
Create Date: 2023-06-01 16:30:19.806693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf03667c1e93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_count', sa.Integer(), nullable=True),
    sa.Column('cpu_utiization', sa.Float(), nullable=True),
    sa.Column('firmware_version', sa.String(length=15), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('macaddr', sa.String(length=15), nullable=True),
    sa.Column('mem_free', sa.Integer(), nullable=True),
    sa.Column('mem_total', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('uplink_ports', sa.String(length=15), nullable=True),
    sa.Column('components_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['components_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('serial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
